site_name: Pelicules Joel
nav:
  - Inici: 'index.md'
  - 'Pelicul·les':
    - 'Forrest Gump': 'forrestGump.md'
    - 'Proyecto X': 'proyectoX.md'
    - 'Annabelle': 'annabelle.md'
    - 'Cars 2': 'cars2.md'
theme: readthedocs